name: Build and Release Binaries

permissions:
  contents: write

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: runninglog-linux
            asset_name: runninglog-linux
          - os: windows-latest
            artifact_name: runninglog-windows
            asset_name: runninglog-windows.exe
          - os: macos-latest
            artifact_name: runninglog-macos
            asset_name: runninglog-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pyinstaller

      - name: List current directory contents
        shell: bash
        run: |
          ls -l

      - name: Build binary with PyInstaller
        run: |
          pyinstaller runninglog.spec

      - name: Create zip archive (Linux/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          cd dist
          zip -r ${{ matrix.artifact_name }}.zip runninglog

      - name: Create zip archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd dist
          Compress-Archive -Path runninglog.exe -DestinationPath ${{ matrix.artifact_name }}.zip

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}.zip
          retention-days: 5

  release:
    name: Release binaries
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Display structure of downloaded files
        run: ls -R dist-artifacts
      
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-artifacts/runninglog-linux/runninglog-linux.zip
            dist-artifacts/runninglog-windows/runninglog-windows.zip
            dist-artifacts/runninglog-macos/runninglog-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
