name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
          pip install black flake8 pytest

      - name: Check formatting with Black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest

      # Optionally, build the package
      - name: Install build tool
        run: python -m pip install build

      - name: Build package
        run: python -m build
